set(CMAKE_SYSTEM_NAME Linux)

set(DEVTOOLSET_ROOT "/opt/rh/devtoolset-11/root/usr" CACHE FILEPATH "" FORCE)

set(CMAKE_C_COMPILER   "${DEVTOOLSET_ROOT}/bin/gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${DEVTOOLSET_ROOT}/bin/g++" CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH "${DEVTOOLSET_ROOT}" CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
